version: '3'

services:

  server:

    build: server/

    tty: True
    
    volumes: 
      - ./server/:/workdir
    
    ports: 
      - 8000:8000


  client:

    build: client/

    network_mode: host

    tty: True

    volumes: 
      - ./client/:/workdir

    depends_on:
     - server

  mongo:

    build: mongodb

    tty: True
      
    volumes:
      - ./mongodb/:/workdir

    ports:
      - 127.0.0.1:27017:27017

    depends_on:
      - server